# Generated by Django 3.1.2 on 2020-12-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0003_person_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=20)),
                ('contracts', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('total_skills', models.IntegerField()),
                ('skill_value_rating', models.IntegerField()),
                ('external_app_link', models.URLField(max_length=50)),
                ('org_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.organization_admin')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.organization')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.state')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('contracts', models.CharField(max_length=30)),
                ('matching_skills', models.IntegerField()),
                ('total_skills', models.IntegerField()),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.applicant')),
                ('job_listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job_listing')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.organization')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.state')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='Resumes')),
                ('citizen', models.IntegerField()),
                ('authorized', models.IntegerField()),
                ('felony', models.IntegerField()),
                ('felony_desc', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.applicant')),
                ('job_listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job_listing')),
                ('orgization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.organization')),
            ],
        ),
    ]
