# Generated by Django 3.1.2 on 2020-12-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='external_app_link',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
