# Generated by Django 3.1.2 on 2020-12-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20201207_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='external_app_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
