# Generated by Django 3.1.1 on 2020-12-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_applicant_organization_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='type',
            field=models.CharField(default='NULL', max_length=20),
            preserve_default=False,
        ),
    ]
