from django import forms
from .models import Applicant, State, Ethnicity, Organization, Organization_Admin
from django.contrib.auth.forms import UserCreationForm

TYPE = {
    ('organization_admin', 'Organization Admin'),
    ('applicant', 'Applicant')
}

class ApplicantUserForm(UserCreationForm):
    phone = forms.CharField(max_length=10)
    city = forms.CharField(max_length=20)
    zip = forms.CharField(max_length=5)
    state = forms.ModelChoiceField(queryset=State.objects.all(), initial=0)
    ethnicity = forms.ModelChoiceField(queryset=Ethnicity.objects.all(), initial=0)
    #country = forms.CharField(max_length=20)
    type = forms.CharField(max_length=20, widget=forms.Select(choices=TYPE))
    #bio = forms.CharField(max_length=20)
    #profile_picture = forms.ImageField()  add a media folder
    website = forms.URLField(max_length=300)
    skill_ai = forms.IntegerField(max_value=4, min_value=0)
    skill_ajax = forms.IntegerField(max_value=4, min_value=0)
    skill_analytical = forms.IntegerField(max_value=4, min_value=0)
    skill_analytics = forms.IntegerField(max_value=4, min_value=0)
    skill_android = forms.IntegerField(max_value=4, min_value=0)
    skill_angular = forms.IntegerField(max_value=4, min_value=0)
    skill_artificial_neural_network = forms.IntegerField(max_value=4, min_value=0)
    skill_asp_net = forms.IntegerField(max_value=4, min_value=0)
    skill_assembleur = forms.IntegerField(max_value=4, min_value=0)
    skill_assembly = forms.IntegerField(max_value=4, min_value=0)
    skill_attention_to_detail = forms.IntegerField(max_value=4, min_value=0)
    skill_backend = forms.IntegerField(max_value=4, min_value=0)
    skill_big_data = forms.IntegerField(max_value=4, min_value=0)
    skill_bootstrap = forms.IntegerField(max_value=4, min_value=0)
    skill_certifications = forms.IntegerField(max_value=4, min_value=0)
    skill_cloud_computing = forms.IntegerField(max_value=4, min_value=0)
    skill_coaching = forms.IntegerField(max_value=4, min_value=0)
    skill_coding = forms.IntegerField(max_value=4, min_value=0)
    skill_collaboration = forms.IntegerField(max_value=4, min_value=0)
    skill_communication = forms.IntegerField(max_value=4, min_value=0)
    skill_communication_technologies = forms.IntegerField(max_value=4, min_value=0)
    skill_consulting = forms.IntegerField(max_value=4, min_value=0)
    skill_content_marketing = forms.IntegerField(max_value=4, min_value=0)
    skill_control_systems = forms.IntegerField(max_value=4, min_value=0)
    skill_critical_thinking = forms.IntegerField(max_value=4, min_value=0)
    skill_customer_service = forms.IntegerField(max_value=4, min_value=0)
    skill_data_analysis = forms.IntegerField(max_value=4, min_value=0)
    skill_data_analytics = forms.IntegerField(max_value=4, min_value=0)
    skill_data_collection = forms.IntegerField(max_value=4, min_value=0)
    skill_data_management = forms.IntegerField(max_value=4, min_value=0)
    skill_data_mining = forms.IntegerField(max_value=4, min_value=0)
    skill_data_processing = forms.IntegerField(max_value=4, min_value=0)
    skill_databases = forms.IntegerField(max_value=4, min_value=0)
    skill_debugging = forms.IntegerField(max_value=4, min_value=0)
    skill_deep_learning = forms.IntegerField(max_value=4, min_value=0)
    skill_design = forms.IntegerField(max_value=4, min_value=0)
    skill_design_patterns = forms.IntegerField(max_value=4, min_value=0)
    skill_designer = forms.IntegerField(max_value=4, min_value=0)
    skill_desk = forms.IntegerField(max_value=4, min_value=0)
    skill_diagnostics = forms.IntegerField(max_value=4, min_value=0)
    skill_digital_marketing = forms.IntegerField(max_value=4, min_value=0)
    skill_documentation = forms.IntegerField(max_value=4, min_value=0)
    skill_dom = forms.IntegerField(max_value=4, min_value=0)
    skill_dos = forms.IntegerField(max_value=4, min_value=0)
    skill_e_commerce = forms.IntegerField(max_value=4, min_value=0)
    skill_eclipse = forms.IntegerField(max_value=4, min_value=0)
    skill_electronics = forms.IntegerField(max_value=4, min_value=0)
    skill_engineering = forms.IntegerField(max_value=4, min_value=0)
    skill_ensemble = forms.IntegerField(max_value=4, min_value=0)
    skill_extjs = forms.IntegerField(max_value=4, min_value=0)
    skill_fortran = forms.IntegerField(max_value=4, min_value=0)
    skill_foundation = forms.IntegerField(max_value=4, min_value=0)
    skill_framework = forms.IntegerField(max_value=4, min_value=0)
    skill_frontend = forms.IntegerField(max_value=4, min_value=0)
    skill_git = forms.IntegerField(max_value=4, min_value=0)
    skill_go = forms.IntegerField(max_value=4, min_value=0)
    skill_graphic_design = forms.IntegerField(max_value=4, min_value=0)
    skill_hadoop = forms.IntegerField(max_value=4, min_value=0)
    skill_hardware = forms.IntegerField(max_value=4, min_value=0)
    skill_hive = forms.IntegerField(max_value=4, min_value=0)
    skill_html = forms.IntegerField(max_value=4, min_value=0)
    skill_http = forms.IntegerField(max_value=4, min_value=0)
    skill_implementation = forms.IntegerField(max_value=4, min_value=0)
    skill_innovation = forms.IntegerField(max_value=4, min_value=0)
    skill_insights = forms.IntegerField(max_value=4, min_value=0)
    skill_internet = forms.IntegerField(max_value=4, min_value=0)
    skill_iphone = forms.IntegerField(max_value=4, min_value=0)
    skill_iptables = forms.IntegerField(max_value=4, min_value=0)
    skill_javascript = forms.IntegerField(max_value=4, min_value=0)
    skill_jquery = forms.IntegerField(max_value=4, min_value=0)
    skill_jsp = forms.IntegerField(max_value=4, min_value=0)
    skill_leadership = forms.IntegerField(max_value=4, min_value=0)
    skill_less = forms.IntegerField(max_value=4, min_value=0)
    skill_linux = forms.IntegerField(max_value=4, min_value=0)
    skill_lte = forms.IntegerField(max_value=4, min_value=0)
    skill_machine_learning = forms.IntegerField(max_value=4, min_value=0)
    skill_mathematics = forms.IntegerField(max_value=4, min_value=0)
    skill_matlab = forms.IntegerField(max_value=4, min_value=0)
    skill_maven = forms.IntegerField(max_value=4, min_value=0)
    skill_mentoring = forms.IntegerField(max_value=4, min_value=0)
    skill_mobile = forms.IntegerField(max_value=4, min_value=0)
    skill_modeling = forms.IntegerField(max_value=4, min_value=0)
    skill_multitasking = forms.IntegerField(max_value=4, min_value=0)
    skill_network_security = forms.IntegerField(max_value=4, min_value=0)
    skill_networks = forms.IntegerField(max_value=4, min_value=0)
    skill_node_js = forms.IntegerField(max_value=4, min_value=0)
    skill_nodejs = forms.IntegerField(max_value=4, min_value=0)
    skill_operating_system = forms.IntegerField(max_value=4, min_value=0)
    skill_organizational = forms.IntegerField(max_value=4, min_value=0)
    skill_pascal = forms.IntegerField(max_value=4, min_value=0)
    skill_penetration_testing = forms.IntegerField(max_value=4, min_value=0)
    skill_phonegap = forms.IntegerField(max_value=4, min_value=0)
    skill_php = forms.IntegerField(max_value=4, min_value=0)
    skill_postfix = forms.IntegerField(max_value=4, min_value=0)
    skill_powershell = forms.IntegerField(max_value=4, min_value=0)
    skill_presentation = forms.IntegerField(max_value=4, min_value=0)
    skill_prestashop = forms.IntegerField(max_value=4, min_value=0)
    skill_priorities = forms.IntegerField(max_value=4, min_value=0)
    skill_problem_solving = forms.IntegerField(max_value=4, min_value=0)
    skill_processing = forms.IntegerField(max_value=4, min_value=0)
    skill_programming = forms.IntegerField(max_value=4, min_value=0)
    skill_project_management = forms.IntegerField(max_value=4, min_value=0)
    skill_project_manager = forms.IntegerField(max_value=4, min_value=0)
    skill_prototyping = forms.IntegerField(max_value=4, min_value=0)
    skill_python = forms.IntegerField(max_value=4, min_value=0)
    skill_renewable_energy = forms.IntegerField(max_value=4, min_value=0)
    skill_reporting = forms.IntegerField(max_value=4, min_value=0)
    skill_reporting_tools = forms.IntegerField(max_value=4, min_value=0)
    skill_sas = forms.IntegerField(max_value=4, min_value=0)
    skill_scrum = forms.IntegerField(max_value=4, min_value=0)
    skill_sencha_touch = forms.IntegerField(max_value=4, min_value=0)
    skill_shiny = forms.IntegerField(max_value=4, min_value=0)
    skill_social_media_marketing = forms.IntegerField(max_value=4, min_value=0)
    skill_software_development = forms.IntegerField(max_value=4, min_value=0)
    skill_solution_development = forms.IntegerField(max_value=4, min_value=0)
    skill_spark = forms.IntegerField(max_value=4, min_value=0)
    skill_sql = forms.IntegerField(max_value=4, min_value=0)
    skill_sql_server = forms.IntegerField(max_value=4, min_value=0)
    skill_statistical_analysis = forms.IntegerField(max_value=4, min_value=0)
    skill_svg = forms.IntegerField(max_value=4, min_value=0)
    skill_swing = forms.IntegerField(max_value=4, min_value=0)
    skill_tableau = forms.IntegerField(max_value=4, min_value=0)
    skill_teamwork = forms.IntegerField(max_value=4, min_value=0)
    skill_tech_support = forms.IntegerField(max_value=4, min_value=0)
    skill_technical = forms.IntegerField(max_value=4, min_value=0)
    skill_telecom = forms.IntegerField(max_value=4, min_value=0)
    skill_time_management = forms.IntegerField(max_value=4, min_value=0)
    skill_training = forms.IntegerField(max_value=4, min_value=0)
    skill_troubleshooting = forms.IntegerField(max_value=4, min_value=0)
    skill_vb_net = forms.IntegerField(max_value=4, min_value=0)
    skill_visio = forms.IntegerField(max_value=4, min_value=0)
    skill_volleyball = forms.IntegerField(max_value=4, min_value=0)
    skill_web_analytics = forms.IntegerField(max_value=4, min_value=0)
    skill_web_development = forms.IntegerField(max_value=4, min_value=0)
    skill_web_services = forms.IntegerField(max_value=4, min_value=0)
    skill_website_development = forms.IntegerField(max_value=4, min_value=0)
    skill_wimax = forms.IntegerField(max_value=4, min_value=0)
    skill_windows = forms.IntegerField(max_value=4, min_value=0)
    skill_word = forms.IntegerField(max_value=4, min_value=0)
    skill_wordpress = forms.IntegerField(max_value=4, min_value=0)

    class Meta:
        model = Applicant
        fields = ('first_name','last_name', 'username', 'email', 'password1' ,'password2' )

class OrgAdminUserForm(UserCreationForm):
    phone = forms.CharField(max_length=10)
    city = forms.CharField(max_length=20)
    zip = forms.CharField(max_length=5)
    state = forms.ModelChoiceField(queryset=State.objects.all(), initial=0)
    ethnicity = forms.ModelChoiceField(queryset=Ethnicity.objects.all(), initial=0)
    #country = forms.CharField(max_length=20)
    type = forms.CharField(max_length=20, widget=forms.Select(choices=TYPE))
    #bio = forms.CharField(max_length=20)
    #profile_picture = forms.ImageField()  add a media folder
    title = forms.CharField(max_length=50)
    organization_id = forms.ModelChoiceField(queryset=Organization.objects.all(), initial=0)

    class Meta:
        model = Organization_Admin
        fields = ('first_name','last_name', 'username', 'email', 'password1' ,'password2', 'phone', 'city', 'zip', 'state', 'ethnicity', 'title', 'organization_id', 'type')
