from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class State(models.Model) :
    state_name = models.CharField(max_length=20)
    state_abbrev = models.CharField(max_length =2)

    def __str__ (self) :
        return(self.state_name)

class Ethnicity(models.Model) :
    ethnicity_name = models.CharField(max_length=30)

    def __str__ (self) :
        return(self.ethnicity_name)

class Person (User) :
    phone = models.CharField(max_length=10)
    city = models.CharField(max_length=20)
    zip = models.CharField(max_length=5)
    state_id = models.OneToOneField("State", on_delete=models.SET_NULL)
    ethnicity = models.OneToOneField("Ethnicity", on_delete=models.SET_NULL)

    class Meta:
        proxy = True

class Organization(models.Model):
    organization_name = models.CharField(max_length=40)
    city = models.CharField(max_length=20)
    state_id = models.OneToOneField(State, on_delete=models.SET_NULL)
    email = models.EmailField(max_length=40)
    size = models.CharField(max_length=20)
    sector = models.CharField(max_length=20)

    def __str__ (self):
        return self.organization_name
class Organization_Admin(Person):
    title = models.CharField(max_length=20)
    organization_id = models.OneToOneField(Organization, on_delete=models.SET_NULL)

    def __str__ (self):
        return(self.first_name + '' + self.last_name)
        pass

class Applicant(Person):
    website = models.CharField(max_length=35)
    skill_ai = models.IntegerField(max_length=1)
    skill_ajax	=	models.IntegerField(max_length=1)
    skill_analytical	=	models.IntegerField(max_length=1)
    skill_analytics	=	models.IntegerField(max_length=1)
    skill_android	=	models.IntegerField(max_length=1)
    skill_angular	=	models.IntegerField(max_length=1)
    skill_artificial neural network	=	models.IntegerField(max_length=1)
    skill_asp.net	=	models.IntegerField(max_length=1)
    skill_assembleur	=	models.IntegerField(max_length=1)
    skill_assembly	=	models.IntegerField(max_length=1)
    skill_attention to detail	=	models.IntegerField(max_length=1)
    skill_backend	=	models.IntegerField(max_length=1)
    skill_big data	=	models.IntegerField(max_length=1)
    skill_bootstrap	=	models.IntegerField(max_length=1)
    skill_certifications	=	models.IntegerField(max_length=1)
    skill_cloud computing	=	models.IntegerField(max_length=1)
    skill_coaching	=	models.IntegerField(max_length=1)
    skill_coding	=	models.IntegerField(max_length=1)
    skill_collaboration	=	models.IntegerField(max_length=1)
    skill_communication	=	models.IntegerField(max_length=1)
    skill_communication technologies	=	models.IntegerField(max_length=1)
    skill_consulting	=	models.IntegerField(max_length=1)
    skill_content marketing	=	models.IntegerField(max_length=1)
    skill_control systems	=	models.IntegerField(max_length=1)
    skill_critical thinking	=	models.IntegerField(max_length=1)
    skill_customer service	=	models.IntegerField(max_length=1)
    skill_data analysis	=	models.IntegerField(max_length=1)
    skill_data analytics	=	models.IntegerField(max_length=1)
    skill_data collection	=	models.IntegerField(max_length=1)
    skill_data management	=	models.IntegerField(max_length=1)
    skill_data mining	=	models.IntegerField(max_length=1)
    skill_data processing	=	models.IntegerField(max_length=1)
    skill_databases	=	models.IntegerField(max_length=1)
    skill_debugging	=	models.IntegerField(max_length=1)
    skill_deep learning	=	models.IntegerField(max_length=1)
    skill_design	=	models.IntegerField(max_length=1)
    skill_design patterns	=	models.IntegerField(max_length=1)
    skill_designer	=	models.IntegerField(max_length=1)
    skill_desk	=	models.IntegerField(max_length=1)
    skill_diagnostics	=	models.IntegerField(max_length=1)
    skill_digital marketing	=	models.IntegerField(max_length=1)
    skill_documentation	=	models.IntegerField(max_length=1)
    skill_dom	=	models.IntegerField(max_length=1)
    skill_dos	=	models.IntegerField(max_length=1)
    skill_e-commerce	=	models.IntegerField(max_length=1)
    skill_eclipse	=	models.IntegerField(max_length=1)
    skill_electronics	=	models.IntegerField(max_length=1)
    skill_engineering	=	models.IntegerField(max_length=1)
    skill_ensemble	=	models.IntegerField(max_length=1)
    skill_extjs	=	models.IntegerField(max_length=1)
    skill_fortran	=	models.IntegerField(max_length=1)
    skill_foundation	=	models.IntegerField(max_length=1)
    skill_framework	=	models.IntegerField(max_length=1)
    skill_frontend	=	models.IntegerField(max_length=1)
    skill_git	=	models.IntegerField(max_length=1)
    skill_go	=	models.IntegerField(max_length=1)
    skill_graphic design	=	models.IntegerField(max_length=1)
    skill_hadoop	=	models.IntegerField(max_length=1)
    skill_hardware	=	models.IntegerField(max_length=1)
    skill_hive	=	models.IntegerField(max_length=1)
    skill_html	=	models.IntegerField(max_length=1)
    skill_http	=	models.IntegerField(max_length=1)
    skill_implementation	=	models.IntegerField(max_length=1)
    skill_innovation	=	models.IntegerField(max_length=1)
    skill_insights	=	models.IntegerField(max_length=1)
    skill_internet	=	models.IntegerField(max_length=1)
    skill_iphone	=	models.IntegerField(max_length=1)
    skill_iptables	=	models.IntegerField(max_length=1)
    skill_javascript	=	models.IntegerField(max_length=1)
    skill_jquery	=	models.IntegerField(max_length=1)
    skill_jsp	=	models.IntegerField(max_length=1)
    skill_leadership	=	models.IntegerField(max_length=1)
    skill_less	=	models.IntegerField(max_length=1)
    skill_linux	=	models.IntegerField(max_length=1)
    skill_lte	=	models.IntegerField(max_length=1)
    skill_machine learning	=	models.IntegerField(max_length=1)
    skill_mathematics	=	models.IntegerField(max_length=1)
    skill_matlab	=	models.IntegerField(max_length=1)
    skill_maven	=	models.IntegerField(max_length=1)
    skill_mentoring	=	models.IntegerField(max_length=1)
    skill_mobile	=	models.IntegerField(max_length=1)
    skill_modeling	=	models.IntegerField(max_length=1)
    skill_multitasking	=	models.IntegerField(max_length=1)
    skill_network security	=	models.IntegerField(max_length=1)
    skill_networks	=	models.IntegerField(max_length=1)
    skill_node.js	=	models.IntegerField(max_length=1)
    skill_nodejs	=	models.IntegerField(max_length=1)
    skill_operating system	=	models.IntegerField(max_length=1)
    skill_organizational	=	models.IntegerField(max_length=1)
    skill_pascal	=	models.IntegerField(max_length=1)
    skill_penetration testing	=	models.IntegerField(max_length=1)
    skill_phonegap	=	models.IntegerField(max_length=1)
    skill_php	=	models.IntegerField(max_length=1)
    skill_postfix	=	models.IntegerField(max_length=1)
    skill_powershell	=	models.IntegerField(max_length=1)
    skill_presentation	=	models.IntegerField(max_length=1)
    skill_prestashop	=	models.IntegerField(max_length=1)
    skill_priorities	=	models.IntegerField(max_length=1)
    skill_problem solving	=	models.IntegerField(max_length=1)
    skill_processing	=	models.IntegerField(max_length=1)
    skill_programming	=	models.IntegerField(max_length=1)
    skill_project management	=	models.IntegerField(max_length=1)
    skill_project manager	=	models.IntegerField(max_length=1)
    skill_prototyping	=	models.IntegerField(max_length=1)
    skill_python	=	models.IntegerField(max_length=1)
    skill_renewable energy	=	models.IntegerField(max_length=1)
    skill_reporting	=	models.IntegerField(max_length=1)
    skill_reporting tools	=	models.IntegerField(max_length=1)
    skill_sas	=	models.IntegerField(max_length=1)
    skill_scrum	=	models.IntegerField(max_length=1)
    skill_sencha touch	=	models.IntegerField(max_length=1)
    skill_shiny	=	models.IntegerField(max_length=1)
    skill_social media marketing	=	models.IntegerField(max_length=1)
    skill_software development	=	models.IntegerField(max_length=1)
    skill_solution development	=	models.IntegerField(max_length=1)
    skill_spark	=	models.IntegerField(max_length=1)
    skill_sql	=	models.IntegerField(max_length=1)
    skill_sql server	=	models.IntegerField(max_length=1)
    skill_statistical analysis	=	models.IntegerField(max_length=1)
    skill_svg	=	models.IntegerField(max_length=1)
    skill_swing	=	models.IntegerField(max_length=1)
    skill_tableau	=	models.IntegerField(max_length=1)
    skill_teamwork	=	models.IntegerField(max_length=1)
    skill_tech support	=	models.IntegerField(max_length=1)
    skill_technical	=	models.IntegerField(max_length=1)
    skill_telecom	=	models.IntegerField(max_length=1)
    skill_time management	=	models.IntegerField(max_length=1)
    skill_training	=	models.IntegerField(max_length=1)
    skill_troubleshooting	=	models.IntegerField(max_length=1)
    skill_vb.net	=	models.IntegerField(max_length=1)
    skill_visio	=	models.IntegerField(max_length=1)
    skill_volleyball	=	models.IntegerField(max_length=1)
    skill_web analytics	=	models.IntegerField(max_length=1)
    skill_web development	=	models.IntegerField(max_length=1)
    skill_web services	=	models.IntegerField(max_length=1)
    skill_website development	=	models.IntegerField(max_length=1)
    skill_wimax	=	models.IntegerField(max_length=1)
    skill_windows	=	models.IntegerField(max_length=1)
    skill_word	=	models.IntegerField(max_length=1)
    skill_wordpress	=	models.IntegerField(max_length=1)

